# Generated by Django 3.1.6 on 2021-07-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210716_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='ControlledAreaStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('number_of_persons_status', models.BooleanField(default=True)),
                ('availability', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userregister')),
            ],
        ),
    ]
